import { iAuction, iAuctionItem } from "./types";

export const mockAuctions: iAuction[] = [
	{
		name: "Electronics Bonanza",
		itemsCount: 10,
		startTime: new Date("2025-11-01T10:00:00Z"),
		duration: 120, // in minutes
		reOpenCount: 2,
		description: "An auction featuring the latest electronics.",
		dateCreated: new Date("2025-10-15T08:00:00Z"),
		createdBy: "admin",
	},
	{
		name: "Fitness Gear Sale",
		itemsCount: 5,
		startTime: new Date("2025-11-05T14:00:00Z"),
		duration: 90,
		reOpenCount: 1,
		description: "Get the best deals on fitness equipment.",
		dateCreated: new Date("2025-10-18T09:30:00Z"),
		createdBy: "admin",
	},
	{
		name: "Home Essentials Auction",
		itemsCount: 3,
		startTime: new Date("2025-11-10T16:00:00Z"),
		duration: 60,
		reOpenCount: 0,
		description: "Bid on essential home appliances.",
		dateCreated: new Date("2025-10-20T11:00:00Z"),
		createdBy: "admin",
	},
];

export const mockItems: iAuctionItem[] = [
	{
		id: "1",
		title: "Smartphone",
		description: "Latest model with advanced features.",
		price: 699,
		image: "/images/b145a819-b176-403f-bbc0-bd2e54a264de.jpeg",
		category: "Electronics",
		condition: "new",
		auction: mockAuctions[0],
	},
	{
		id: "2",
		title: "Laptop",
		description: "High-performance laptop for work and gaming.",
		price: 1299,
		image: "/images/b145a819-b176-403f-bbc0-bd2e54a264de.jpeg",
		category: "Electronics",
		condition: "new",
		auction: mockAuctions[0],
	},
	{
		id: "3",
		title: "Headphones",
		description: "Noise-cancelling headphones with great sound quality.",
		price: 199,
		image: "/images/b145a819-b176-403f-bbc0-bd2e54a264de.jpeg",
		category: "Electronics",
		condition: "new",
		auction: mockAuctions[1],
	},
	{
		id: "4",
		title: "Smartwatch",
		description: "Track your fitness and stay connected on the go.",
		price: 299,
		image: "/images/b145a819-b176-403f-bbc0-bd2e54a264de.jpeg",
		category: "Electronics",
		condition: "new",
		auction: mockAuctions[1],
	},
	{
		id: "5",
		title: "Tablet",
		description: "Portable and powerful tablet for work and play.",
		price: 499,
		image: "/images/b145a819-b176-403f-bbc0-bd2e54a264de.jpeg",
		category: "Electronics",
		condition: "new",
		auction: mockAuctions[2],
	},
	{
		id: "6",
		title: "Camera",
		description: "Capture stunning photos and videos.",
		price: 899,
		image: "/images/b145a819-b176-403f-bbc0-bd2e54a264de.jpeg",
		category: "Electronics",
		condition: "new",
		auction: mockAuctions[2],
	},
	{
		id: "7",
		title: "Gaming Console",
		description: "Next-gen console for immersive gaming.",
		price: 599,
		image: "/images/b145a819-b176-403f-bbc0-bd2e54a264de.jpeg",
		category: "Electronics",
		condition: "new",
		auction: mockAuctions[1],
	},
	{
		id: "8",
		title: "Wireless Earbuds",
		description: "Compact and high-quality sound.",
		price: 149,
		image: "/images/b145a819-b176-403f-bbc0-bd2e54a264de.jpeg",
		category: "Electronics",
		condition: "new",
		auction: mockAuctions[0],
	},
	{
		id: "9",
		title: "Smart TV",
		description: "4K Ultra HD with streaming capabilities.",
		price: 999,
		image: "/images/b145a819-b176-403f-bbc0-bd2e54a264de.jpeg",
		category: "Electronics",
		condition: "new",
		auction: mockAuctions[0],
	},
	{
		id: "10",
		title: "Fitness Tracker",
		description: "Monitor your health and activity levels.",
		price: 99,
		image: "/images/b145a819-b176-403f-bbc0-bd2e54a264de.jpeg",
		category: "Fitness",
		condition: "new",
		auction: mockAuctions[1],
	},
	{
		id: "11",
		title: "Bluetooth Speaker",
		description: "Portable speaker with excellent sound quality.",
		price: 129,
		image: "/images/b145a819-b176-403f-bbc0-bd2e54a264de.jpeg",
		category: "Electronics",
		condition: "new",
		auction: mockAuctions[2],
	},
	{
		id: "12",
		title: "Drone",
		description: "Capture aerial views with ease.",
		price: 799,
		image: "/images/b145a819-b176-403f-bbc0-bd2e54a264de.jpeg",
		category: "Electronics",
		condition: "new",
		auction: mockAuctions[2],
	},
	{
		id: "13",
		title: "Electric Scooter",
		description: "Eco-friendly and fun transportation.",
		price: 499,
		image: "/images/b145a819-b176-403f-bbc0-bd2e54a264de.jpeg",
		category: "Vehicles",
		condition: "new",
		auction: mockAuctions[2],
	},
	{
		id: "14",
		title: "Gaming Chair",
		description: "Ergonomic chair for long gaming sessions.",
		price: 199,
		image: "/images/b145a819-b176-403f-bbc0-bd2e54a264de.jpeg",
		category: "Furniture",
		condition: "new",
		auction: mockAuctions[2],
	},
	{
		id: "15",
		title: "Mechanical Keyboard",
		description: "Tactile and responsive typing experience.",
		price: 89,
		image: "/images/b145a819-b176-403f-bbc0-bd2e54a264de.jpeg",
		category: "Electronics",
		condition: "new",
		auction: mockAuctions[0],
	},
	{
		id: "16",
		title: "Monitor",
		description: "High-resolution display for work and gaming.",
		price: 299,
		image: "/images/b145a819-b176-403f-bbc0-bd2e54a264de.jpeg",
		category: "Electronics",
		condition: "new",
		auction: mockAuctions[1],
	},
	{
		id: "17",
		title: "VR Headset",
		description: "Immerse yourself in virtual reality.",
		price: 399,
		image: "/images/b145a819-b176-403f-bbc0-bd2e54a264de.jpeg",
		category: "Electronics",
		condition: "new",
		auction: mockAuctions[1],
	},
	{
		id: "18",
		title: "External Hard Drive",
		description: "Expand your storage capacity.",
		price: 79,
		image: "/images/b145a819-b176-403f-bbc0-bd2e54a264de.jpeg",
		category: "Electronics",
		condition: "new",
		auction: mockAuctions[2],
	},
	{
		id: "19",
		title: "Smart Home Hub",
		description: "Control your smart devices with ease.",
		price: 149,
		image: "/images/b145a819-b176-403f-bbc0-bd2e54a264de.jpeg",
		category: "Electronics",
		condition: "new",
		auction: mockAuctions[2],
	},
	{
		id: "20",
		title: "Electric Kettle",
		description: "Boil water quickly and efficiently.",
		price: 49,
		image: "/images/b145a819-b176-403f-bbc0-bd2e54a264de.jpeg",
		category: "Home Appliances",
		condition: "new",
		auction: mockAuctions[2],
	},
];
