import type { Metadata } from "next";
import { StackProvider, StackTheme } from "@stackframe/stack";
import { stackServerApp } from "../stack";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/Footer";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const customTheme = {
	light: {
		background: "#f5faff", // Resolved value for var(--color-background)
		foreground: "#00263f", // Resolved value for var(--color-foreground)
		card: "#f2f5fa", // Resolved value for var(--color-card)
		cardForeground: "#1a3a5f", // Resolved value for var(--color-card-foreground)
		popover: "#f2f5fa", // Resolved value for var(--color-popover)
		popoverForeground: "#1a3a5f", // Resolved value for var(--color-popover-foreground)
		primary: "#41b3ff", // Resolved value for var(--color-primary)
		primaryForeground: "#ffffff", // Resolved value for var(--color-primary-foreground)
		secondary: "#82afce", // Resolved value for var(--color-secondary)
		secondaryForeground: "#ffffff", // Resolved value for var(--color-secondary-foreground)
		muted: "#e6eef5", // Resolved value for var(--color-muted)
		mutedForeground: "#4a5f73", // Resolved value for var(--color-muted-foreground)
		accent: "#007ea7", // Resolved value for var(--color-accent)
		accentForeground: "#ffffff", // Resolved value for var(--color-accent-foreground)
		destructive: "#ff4d4d", // Resolved value for var(--color-destructive)
		destructiveForeground: "#ffffff", // Resolved value for var(--color-foreground)
		border: "#d1e3f0", // Resolved value for var(--color-border)
		input: "#f2f5fa", // Resolved value for var(--color-input)
		ring: "#41b3ff", // Resolved value for var(--color-ring)
	},
	dark: {
		background: "#1a1a2e", // Resolved value for var(--background)
		foreground: "#e0e0e0", // Resolved value for var(--foreground)
		card: "#2a2a3e", // Resolved value for var(--card)
		cardForeground: "#d0d0d0", // Resolved value for var(--card-foreground)
		popover: "#2a2a3e", // Resolved value for var(--popover)
		popoverForeground: "#d0d0d0", // Resolved value for var(--popover-foreground)
		primary: "#41b3ff", // Resolved value for var(--primary)
		primaryForeground: "#ffffff", // Resolved value for var(--primary-foreground)
		secondary: "#82afce", // Resolved value for var(--secondary)
		secondaryForeground: "#ffffff", // Resolved value for var(--secondary-foreground)
		muted: "#2e2e4e", // Resolved value for var(--muted)
		mutedForeground: "#a0a0b0", // Resolved value for var(--muted-foreground)
		accent: "#007ea7", // Resolved value for var(--accent)
		accentForeground: "#ffffff", // Resolved value for var(--accent-foreground)
		destructive: "#ff4d4d", // Resolved value for var(--destructive)
		destructiveForeground: "#ffffff", // Resolved value for var(--foreground)
		border: "#3a3a5e", // Resolved value for var(--border)
		input: "#2a2a3e", // Resolved value for var(--input)
		ring: "#41b3ff", // Resolved value for var(--ring)
	},
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`antialiased`}>
				<StackProvider app={stackServerApp}>
					<StackTheme theme={customTheme}>
						<Header />
						<main>{children}</main>
						<Toaster />
						<Footer />
					</StackTheme>
				</StackProvider>
			</body>
		</html>
	);
}
