import type { Metadata } from "next";
import { StackProvider, StackTheme } from "@stackframe/stack";
import { stackServerApp } from "../stack";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/Footer";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const customTheme = {
	light: {
		background: "#f5faff",
		foreground: "#00263f",
		card: "#f2f5fa",
		cardForeground: "#1a3a5f",
		popover: "#f2f5fa",
		popoverForeground: "#1a3a5f",
		primary: "#41b3ff",
		primaryForeground: "#ffffff",
		secondary: "#82afce",
		secondaryForeground: "#ffffff",
		muted: "#e6eef5",
		mutedForeground: "#4a5f73",
		accent: "#007ea7",
		accentForeground: "#ffffff",
		destructive: "#ff4d4d",
		destructiveForeground: "#ffffff",
		border: "#d1e3f0",
		input: "#f2f5fa",
		ring: "#41b3ff",
	},
	dark: {
		background: "#1a1a2e",
		foreground: "#e0e0e0",
		card: "#2a2a3e",
		cardForeground: "#d0d0d0",
		popover: "#2a2a3e",
		popoverForeground: "#d0d0d0",
		primary: "#41b3ff",
		primaryForeground: "#ffffff",
		secondary: "#82afce",
		secondaryForeground: "#ffffff",
		muted: "#2e2e4e",
		mutedForeground: "#a0a0b0",
		accent: "#007ea7",
		accentForeground: "#ffffff",
		destructive: "#ff4d4d",
		destructiveForeground: "#ffffff",
		border: "#3a3a5e",
		input: "#2a2a3e",
		ring: "#41b3ff",
	},
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`antialiased`}>
				<StackProvider app={stackServerApp}>
					<StackTheme theme={customTheme}>
						<Header />
						<main>{children}</main>
						<Toaster />
						<Footer />
					</StackTheme>
				</StackProvider>
			</body>
		</html>
	);
}
