DROP TABLE IF EXISTS emails;
CREATE TABLE emails (
	id SERIAL PRIMARY KEY,
	from_email VARCHAR(255) NOT NULL,
	to_email VARCHAR(255) NOT NULL,
	subject VARCHAR(255) NOT NULL,
	body TEXT NOT NULL,
	status VARCHAR(32) NOT NULL DEFAULT 'SENT',
	date_sent TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
